
# Copy this file to _config.local.yml and update the content.
# Then use this command to build the project.
# $ jekyll build --config _config.yml,_config.local.yml

baseurl: "" # The folder in which the site is located on the web server.
url: "http://dgthree-local.dev" # Without a trailing slash!

# URL for the "Follow Us" contact link.
contact: /connect

# URL for the newsletter subscribe form.
mailchimp_form_url: __NONE__

# Google Analytics Web Property ID.
google_web_property_id: __NONE__

# Uncomment on localhost so that you don't wait forever for the build to finish.
# limit_posts: 40
