
#---------------#
# Site settings #
#---------------#

title: Development Gateway
email: info@developmentgateway.org
description: >
  An interactive portal for information and knowledge sharing on sustainable development and poverty reduction.
  Includes comprehensive database of development projects and an international procurement marketplace.

# The current year is added befor the copyright text.
copyright: >
  Development Gateway and/or its affiliated companies

baseurl: ""
url: ""


#-----------------#
# Jekyll settings #
#-----------------#

# Exclude files/folders from being processed by Jekyll and copied to the built website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile
  - Vagrantsettings.yaml
# NOTE: All the files/folders starting with "_" (underscore) are also excluded.

# Set the default markdown processor.
markdown: kramdown

# Change the default SASS settings.
sass:
  sass_dir: _scss
