
#---------------#
# Site settings #
#---------------#

title: Development Gateway
email: info@developmentgateway.org
description: >
  An interactive portal for information and knowledge sharing on sustainable development and poverty reduction.
  Includes comprehensive database of development projects and an international procurement marketplace.

# The current year is added befor the copyright text.
copyright: >
  Development Gateway and/or its affiliated companies

# Map config for the reach page
map:
  tiles: "https://api.tiles.mapbox.com/v4/pschleihauf.lcn2c8c1/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoicHNjaGxlaWhhdWYiLCJhIjoiMWtmWlNOTSJ9._M5g6v6M6LskiUHkhSjOHQ&secure=1"
  minZoom: 1
  maxZoom: 5

baseurl: "/" # The folder in which the site is located on the web server.
url: ""

# Define image presets for the image tag plugin.
image:
  presets:
    avatar_small:
      width: 144
      height: 144
    flag_small:
      width: 64
      height: 32
    thumb_small:
      width: 240
      height: 160
    thumb_large:
      # 19 * 1em
      width: 304
      # 12 * 1em
      height: 192

collections:
  homepage_sections:
    output: true
  expertise_topics:
    output: true

# URL for the mailchimp newsletter.
mailchimp_form_url: __NONE__

# Google Analytics Web Property ID.
google_web_property_id: __NONE__

#-----------------#
# Jekyll settings #
#-----------------#

# Exclude files/folders from being processed by Jekyll and copied to the built website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile
  - Vagrantsettings.yaml
# NOTE: All the files/folders starting with "_" (underscore) are also excluded.

# Set the default markdown processor.
markdown: kramdown

# Change the default SASS settings.
sass:
  sass_dir: _scss

# Uncomment the following lines to enable lunr.js search.
#gems:
#  - 'jekyll-lunr-js-search'

# lunr.js specific settings.
lunr_search:
  excludes:
    - blog.html
    - expertise/topics.json
    - feed.xml
    - images
    - lib
    - scripts
  js_dir: scripts
