
#---------------#
# Site settings #
#---------------#

title: Development Gateway
email: info@developmentgateway.org
description: >
  An international nonprofit that co-creates information solutions and cultivates skills to turn information into lasting results.
#keywords: []

# The current year is added before the copyright text.
copyright: >
  Development Gateway and/or its affiliated companies

# Map config for the reach page
map:
  tiles: ~
  minZoom: 1
  maxZoom: 5

baseurl: "" # The folder in which the site is located on the web server.
url: "" # Without a trailing slash!

# Define image presets for the image tag plugin.
image:
  presets:
    avatar-small:
      width: 144
      height: 144
    flag-small:
      width: 64
      height: 32
      resize: scale
    thumb-small:
      width: 240
      height: 160
    thumb-home:
      # 17 * 1em
      width: 272
      # 12 * 1em
      height: 192
    thumb-large:
      # 19 * 1em
      width: 304
      # 12 * 1em
      height: 192

# Define settings and presets for the icon tag plugin.
icon:
  source: images/icons
  presets:
    normal:
      width: 1em
      height: 1em
    larger:
      width: 1.125em
      height: 1.125em

# Define the available jekyll collections.
collections:
  homepage_sections:
    output: false
  expertise_topics:
    output: true

# URL for the MailChimp newsletter.
mailchimp_form_url: __NONE__

# Google Analytics Web Property ID.
google_web_property_id: __NONE__

#-----------------#
# Jekyll settings #
#-----------------#

# Change jekyll build source and destination.
source: site_source
destination: public_html

# Blog listing pagination settings.
paginate: 10
paginate_path: "/blog/page:num/"

# Change the default blog post link.
permalink: "/:year/:month/:day/:title"

# Exclude files/folders from being processed by Jekyll and copied to the built website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile
  - Vagrantsettings.yml
  - Vagrantsettings.local.yml
# NOTE: All the files/folders starting with "_" (underscore) are also excluded.

# Set the default markdown processor.
markdown: kramdown

# Change the default SASS settings.
sass:
  sass_dir: _scss

# Variables that can be printed inside SASS files.
# @TODO: Implement a way to inject variables into the compliation process.
sass_variables:
  gen_total_columns: '12'
  gen_column_width: '4em'
  gen_gutter_width: '1em'
  sidebar_grid_count: '3'
  content_grid_count: '9'

# Uncomment the `jekyll-lunr-js-search` line to enable lunr.js search.
# The site `url` needs to be setup for jekyll-sitemap to work properly.
gems:
  - jekyll-sitemap
  - jekyll-lunr-js-search

# lunr.js specific settings.
lunr_search:
  excludes:
    - blog/index.html
    - expertise/topics.json
    - feed.xml
    - images
    - lib
    - scripts
  js_dir: scripts

# prose.io specific settings.
prose:
  media: assets/post-images
  ignore:
    - .editorconfig
    - .gitignore
    - .ruby-gemset
    - .ruby-version
    - _config.sample.yml
    - _config.yml
    - Gemfile
    - Makefile
    - site_source/_data
    - site_source/_html
    - site_source/_includes
    - site_source/_layouts
    - site_source/_plugins
    - site_source/_posts
    - site_source/_scss
    - site_source/lib
    - site_source/scripts
    - site_source/styles
    - site_source/browserconfig.xml
    - site_source/favicon.ico
    - site_source/feed.xml
    - site_source/index.html
    - site_source/main.js
    - site_source/robots_sample.txt
    - site_source/search.html
